/**
 * Hardened executor for model-authored simulation code.
 *
 * The pre-lab simulator asks the design model to WRITE a self-contained
 * JavaScript Monte-Carlo program, then runs it here to get real numbers (this
 * is the OpenScience "write-and-run-code" pattern, adapted to our runtime).
 *
 * SECURITY / TRUST MODEL:
 *  - `node:vm` is NOT a hard security boundary on its own. We rely on it being
 *    safe ENOUGH given the trust model, and harden accordingly:
 *  - The code is generated by our OWN trusted model from a FIXED prompt — it is
 *    never user-supplied text. The user only supplies a design description that
 *    the model reads; it does not reach the sandbox as code.
 *  - We inject ONLY primitives (`SEED`, and `PARAMS` as a plain data object) —
 *    NO host functions, NO host constructors (Math/JSON/Array/console are the
 *    context's own intrinsics, not the host's), so there is no host object to
 *    pivot through (the classic `injected.constructor.constructor("…")()`
 *    escape needs a host object; we expose none).
 *  - A synchronous `timeout` gives a hard wall-clock bound (works precisely
 *    because the program is pure synchronous computation).
 *  - The result is deep-cloned through JSON on the way out, severing any
 *    prototype links back into the sandbox context.
 *
 * The program contract (enforced by prompt + validated here):
 *  - Pure synchronous JS. No imports/require, no async, no I/O.
 *  - Reads the injected globals `SEED` (number) and `PARAMS` (object of
 *    name → number). Defines its own PRNG seeded from SEED.
 *  - Assigns its JSON-serializable output to the global `RESULT`.
 */
import vm from "node:vm"

export interface SandboxRun {
  ok: boolean
  /** The JSON-cloned value the program assigned to `RESULT`. */
  output?: any
  error?: string
  ms: number
}

const MAX_CODE_CHARS = 40_000

export function runSimSandbox(
  code: string,
  opts?: { seed?: number; params?: Record<string, number>; timeoutMs?: number }
): SandboxRun {
  const started = Date.now()
  const seed = Number.isFinite(opts?.seed) ? (opts!.seed as number) : 1_234_567
  const timeout = Math.min(Math.max(opts?.timeoutMs ?? 4000, 200), 15_000)

  if (typeof code !== "string" || !code.trim()) {
    return { ok: false, error: "empty simulation code", ms: 0 }
  }
  if (code.length > MAX_CODE_CHARS) {
    return {
      ok: false,
      error: `simulation code too long (${code.length} chars)`,
      ms: 0
    }
  }
  // Cheap static guard against obviously-forbidden constructs. Not a security
  // boundary (the vm isolation is) — just a fast fail with a clear reason so a
  // malformed program falls back to the reasoned path instead of timing out.
  if (/\b(require|import|process|globalThis|eval|Function\s*\()/.test(code)) {
    return {
      ok: false,
      error: "simulation code used a forbidden construct",
      ms: 0
    }
  }

  // Only PRIMITIVE data crosses the boundary. `PARAMS` is rebuilt as a fresh
  // plain object of numbers so no host reference leaks in.
  const params: Record<string, number> = {}
  if (opts?.params) {
    for (const [k, v] of Object.entries(opts.params)) {
      if (typeof v === "number" && Number.isFinite(v)) params[k] = v
    }
  }

  const sandbox: Record<string, any> = {
    SEED: seed,
    PARAMS: params,
    RESULT: undefined
  }

  try {
    const context = vm.createContext(sandbox, {
      name: "design-sim",
      codeGeneration: { strings: false, wasm: false }
    })
    vm.runInContext(`"use strict";\n${code}`, context, {
      timeout,
      displayErrors: true
    })
    const out = sandbox.RESULT
    if (out === undefined || out === null) {
      return {
        ok: false,
        error: "program set no RESULT",
        ms: Date.now() - started
      }
    }
    let cloned: any
    try {
      cloned = JSON.parse(JSON.stringify(out))
    } catch {
      return {
        ok: false,
        error: "RESULT was not JSON-serializable",
        ms: Date.now() - started
      }
    }
    return { ok: true, output: cloned, ms: Date.now() - started }
  } catch (e: any) {
    const msg: string = e?.message ?? String(e)
    return {
      ok: false,
      error: /timed out/i.test(msg) ? "simulation timed out" : msg,
      ms: Date.now() - started
    }
  }
}
