"use client"

import {
  IconBulb,
  IconChartBar,
  IconClipboardText,
  IconPaperclip,
  IconSparkles,
  IconX
} from "@tabler/icons-react"
import { useParams, useRouter } from "next/navigation"
import { FC, useContext, useEffect, useRef, useState } from "react"
import { toast } from "sonner"

import { ChatbotUIContext } from "@/context/context"
import { useDesignContext } from "@/context/designcontext"
import { linkDesignToProject } from "@/db/designs"
import { createDesign, updateDesign } from "@/db/designs-firestore"
import { getProjectsByWorkspaceId } from "@/db/projects"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"

/**
 * CreateDesign supports three creation modes:
 *
 *   "from-scratch"   - name only; user fills problem/literature/hypotheses/design.
 *   "from-hypothesis" - user supplies a hypothesis up front; design is seeded
 *                       with that hypothesis pre-approved so the user can
 *                       generate an experiment design immediately.
 *   "from-plan"      - user pastes a draft procedure; stored on the design
 *                       so the design-generation agent uses it as priming
 *                       context. The pipeline still fills the SOP sections.
 */
/**
 * Modes the create-design dialog supports.
 *
 * Shadow-generated flows:
 *   "from-scratch"     - full 5-stage flow
 *   "from-hypothesis"  - user supplies hypothesis, jump to design phase
 *   "from-plan"        - user pastes draft procedure, agent fills SOP gaps
 *
 * External-design flows (operate on a design the user brings in, NOT one
 * generated by Shadow AI):
 *   "check-stats"      - user pastes / uploads an existing design; Shadow
 *                         reviews the stats plan (power, test choice, n)
 *   "make-plan"        - user pastes / uploads an existing design; Shadow
 *                         produces a dated execution plan
 */
export type CreateDesignMode =
  | "from-scratch"
  | "from-hypothesis"
  | "from-plan"
  | "check-stats"
  | "make-plan"

const EXTERNAL_DESIGN_MODES: CreateDesignMode[] = ["check-stats", "make-plan"]

interface CreateDesignProps {
  isOpen: boolean
  onOpenChange: (isOpen: boolean) => void
  projectId?: string | null
  mode?: CreateDesignMode
  /** Optional seed text from the dashboard quick-start composer. */
  initialQuery?: string
}

const MODE_COPY: Record<
  CreateDesignMode,
  {
    title: string
    subtitle: string
    icon: typeof IconSparkles
    cta: string
  }
> = {
  "from-scratch": {
    title: "New design",
    subtitle: "Add your design title here.",
    icon: IconSparkles,
    cta: "Create"
  },
  "from-hypothesis": {
    title: "Design from a hypothesis",
    subtitle:
      "You supply the hypothesis; Shadow AI jumps to experiment design. Problem + Literature + Hypothesis phases are pre-approved.",
    icon: IconBulb,
    cta: "Seed and open"
  },
  "from-plan": {
    title: "Structure an existing plan",
    subtitle:
      "Paste your draft procedure. The design agent will slot it into the SOP sections and fill the gaps.",
    icon: IconClipboardText,
    cta: "Create"
  },
  "check-stats": {
    title: "Check a design statistically",
    subtitle:
      "Paste or upload an existing design (from a paper, a colleague, or your draft). Shadow reviews the stats plan: power, test choice, sample size.",
    icon: IconChartBar,
    cta: "Check stats"
  },
  "make-plan": {
    title: "Make a plan for a design",
    subtitle:
      "Paste or upload an existing design. Shadow produces a dated execution plan with owners and checkpoints.",
    icon: IconClipboardText,
    cta: "Make a plan"
  }
}

const ACCEPTED_UPLOAD_TYPES =
  ".pdf,.csv,.docx,.txt,application/pdf,text/csv,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document"

export const CreateDesign: FC<CreateDesignProps> = ({
  isOpen,
  onOpenChange,
  projectId,
  mode = "from-scratch",
  initialQuery = ""
}) => {
  const { profile, selectedWorkspace, designs, setDesigns } =
    useContext(ChatbotUIContext)
  const { setSelectedDesign } = useDesignContext()

  const router = useRouter()
  const params = useParams()

  const [name, setName] = useState("")
  const [problem, setProblem] = useState("")
  const [hypothesis, setHypothesis] = useState("")
  const [planText, setPlanText] = useState("")
  /** External-design content for check-stats / make-plan modes. */
  const [externalDesignText, setExternalDesignText] = useState("")
  /** Files attached to the new design (every mode supports this). */
  const [attachedFiles, setAttachedFiles] = useState<File[]>([])
  const [creating, setCreating] = useState(false)
  const nameRef = useRef<HTMLInputElement>(null)

  // Project dropdown - scientists asked for the new-design dialog to
  // pin which project the design lives under. "none" is the sentinel
  // for "workspace-level, no project". Defaults to whatever projectId
  // the caller passed (e.g. when launched from inside a project's
  // canvas) so we don't ask twice.
  const [projects, setProjects] = useState<{ id: string; name: string }[]>([])
  const [selectedProjectId, setSelectedProjectId] = useState<string | "none">(
    projectId ?? "none"
  )

  const isExternalMode = EXTERNAL_DESIGN_MODES.includes(mode)
  // PDFs are now allowed on from-hypothesis too so the scientist can
  // attach supporting papers next to the hypothesis they're seeding.
  // From-scratch + from-plan still skip the picker (lit-tab uploads
  // cover them) - we don't want every mode showing a file row.
  const canAttachFiles = isExternalMode || mode === "from-hypothesis"

  useEffect(() => {
    if (!isOpen) return
    // Seed fields on open. If the user composed a query on the dashboard,
    // prefill it into the primary text field for the current mode.
    //
    // For from-scratch we intentionally do NOT prefill the Name with the
    // dashboard query - the query is usually a research-question / problem
    // statement, not a title. Instead it seeds the Problem page after
    // create (see handleCreate). The user types a short title in the
    // dialog and lands on the Problem page with the problem pre-populated.
    if (mode === "from-scratch") {
      setName("")
      setProblem("") // Problem field is hidden for from-scratch; seeded server-side from initialQuery.
    } else {
      setName(initialQuery.slice(0, 80))
      setProblem(initialQuery)
    }
    setHypothesis("")
    setPlanText("")
    setExternalDesignText("")
    setAttachedFiles([])
    setSelectedProjectId(projectId ?? "none")
    setTimeout(() => nameRef.current?.focus(), 0)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, mode, projectId])

  // Load projects on first open so the picker has options. Best-effort -
  // a fetch failure just shows "(no project)" as the only choice.
  useEffect(() => {
    if (!isOpen || !selectedWorkspace?.id) return
    let cancelled = false
    void getProjectsByWorkspaceId(selectedWorkspace.id)
      .then((rows: any[]) => {
        if (!cancelled) {
          setProjects(
            (rows ?? []).map((p: any) => ({
              id: p.id as string,
              name: p.name as string
            }))
          )
        }
      })
      .catch((err: any) =>
        console.warn("[CreateDesign] failed to load projects:", err)
      )
    return () => {
      cancelled = true
    }
  }, [isOpen, selectedWorkspace?.id])

  if (!profile || !selectedWorkspace) return null

  const copy = MODE_COPY[mode]
  const HeaderIcon = copy.icon

  const canSubmit = (() => {
    if (creating) return false
    if (!name.trim()) return false
    if (mode === "from-hypothesis" && hypothesis.trim().length < 10)
      return false
    if (mode === "from-plan" && planText.trim().length < 20) return false
    if (isExternalMode) {
      // Need either pasted content or an uploaded file to operate on.
      const hasPaste = externalDesignText.trim().length >= 20
      const hasFile = attachedFiles.length > 0
      if (!hasPaste && !hasFile) return false
    }
    return true
  })()

  const handleCreate = async () => {
    const trimmedName = name.trim()
    if (!trimmedName) return

    setCreating(true)
    try {
      // For from-scratch, the Problem field is hidden in the dialog (user
      // fills it on the Problem page) - but if they came in from a dashboard
      // quick-start composer with `?q=...`, that text IS the problem
      // statement and we seed it so the Problem page is pre-populated
      // instead of asking the user to retype.
      const seededProblem =
        mode === "from-scratch" ? initialQuery.trim() : problem.trim()

      // Prefer the dropdown selection over the caller's `projectId` so a
      // user opening the dialog from inside a project canvas can still
      // override and file the design at workspace level.
      const finalProjectId =
        selectedProjectId === "none" ? null : selectedProjectId

      // 1) Create the base design row (Supabase).
      const created = await createDesign(
        {
          user_id: profile.user_id,
          name: trimmedName,
          problem: seededProblem || trimmedName,
          description: (seededProblem || trimmedName).slice(0, 240),
          sharing: "private" as const,
          objectives: [],
          variables: [],
          specialConsiderations: [],
          project_id: finalProjectId
        },
        selectedWorkspace.id
      )

      if (
        finalProjectId &&
        created?.id &&
        created.project_id !== finalProjectId
      ) {
        try {
          await linkDesignToProject(created.id, finalProjectId)
          created.project_id = finalProjectId
        } catch (err) {
          console.warn("Failed to link new design to project:", err)
        }
      }

      // 2) Mode-specific post-create seeding.
      // From-scratch: stash the user-supplied title + problem into structured
      // content.problem so the design-detail loader reads from there directly
      // (avoiding the data.description fallback path which has historically
      // produced subtle prefill bugs).
      if (mode === "from-scratch" && created?.id) {
        // Always seed `content.problem.title` from the Name input so the
        // Problem page shows the dialog title verbatim instead of falling
        // through to `data.description`. Seed `problemStatement` if we
        // captured one from the dashboard quick-start (`?q=...`).
        const seededContent = {
          schemaVersion: 2,
          approvedPhases: [],
          problem: {
            title: trimmedName,
            problemStatement: seededProblem,
            objective: "",
            goal: ""
          },
          papers: [],
          hypotheses: []
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn("Failed to seed from-scratch content:", err)
        }
      }

      // For hypothesis mode, pre-seed the design content so the downstream
      // design-detail page opens ready to generate an experiment design
      // (problem / literature / hypotheses phases are marked approved).
      if (mode === "from-hypothesis" && created?.id) {
        const hypText = hypothesis.trim()
        const problemText = problem.trim() || trimmedName
        const seededContent = {
          schemaVersion: 2,
          approvedPhases: ["problem", "literature", "hypotheses"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText
          },
          papers: [],
          hypotheses: [
            {
              id: `h-${Date.now()}`,
              text: hypText,
              reasoning: "User-provided hypothesis.",
              basedOnPaperIds: [],
              selected: true,
              userSupplied: true
            }
          ]
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn(
            "Failed to seed hypothesis-mode content; user can re-enter in the design:",
            err
          )
        }
      }

      if (mode === "from-plan" && created?.id) {
        // Stash the user-supplied plan on the design's problem text so the
        // generation agents pick it up as priming context. Backend prompt
        // changes can promote this to its own field later.
        const planned = planText.trim()
        const problemText = problem.trim() || trimmedName
        const seededContent = {
          schemaVersion: 2,
          approvedPhases: ["problem"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText,
            userProvidedPlan: planned
          },
          papers: [],
          hypotheses: []
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn("Failed to seed plan-mode content:", err)
        }
      }

      // External-design modes (check-stats / make-plan): the design is
      // brought in by the user - Shadow AI does NOT generate it. We stuff
      // the pasted text into a single synthetic generated-design so the
      // existing stats-review and make-plan endpoints (which read from
      // `content.designs[]`) can operate on it.
      if (isExternalMode && created?.id) {
        const ext = externalDesignText.trim()
        const problemText = problem.trim() || trimmedName
        const designId = `ext-${Date.now()}`
        const seededContent = {
          schemaVersion: 2,
          external: true,
          approvedPhases: ["problem", "literature", "hypotheses", "design"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText
          },
          papers: [],
          hypotheses: [],
          designs: [
            {
              id: designId,
              title: trimmedName,
              hypothesisId: null,
              external: true,
              sections: [
                {
                  heading: "External Design",
                  body: ext
                }
              ],
              attachments: attachedFiles.map(f => ({
                name: f.name,
                size: f.size,
                type: f.type
              }))
            }
          ]
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn("Failed to seed external-design content:", err)
        }
      }

      // Capture file metadata on every other mode too so downstream agents
      // can see what the user attached. Real upload to storage is wired up
      // by the design-detail page's existing PDF-upload handler - for now
      // we record names + sizes only.
      if (!isExternalMode && attachedFiles.length > 0 && created?.id) {
        try {
          await updateDesign(created.id, {
            content_attachments: attachedFiles.map(f => ({
              name: f.name,
              size: f.size,
              type: f.type
            }))
          } as any)
        } catch (err) {
          console.warn("Failed to record attachment metadata:", err)
        }
      }

      setDesigns([created, ...designs])
      setSelectedDesign(created)

      const locale = (params.locale as string) ?? "en"
      const wsId = params.workspaceid as string

      // Routing per mode. The design detail page reads `?tab=` to
      // open on a non-Problem tab when the user already supplied
      // upstream content - otherwise every flavour landed back on
      // Problem with the user re-typing what they already typed in
      // the dialog (scientist's complaint).
      let qs = ""
      if (mode === "check-stats") {
        qs = "?auto=stats-review&tab=design"
      } else if (mode === "make-plan") {
        qs = "?auto=make-plan&tab=design"
      } else if (mode === "from-hypothesis") {
        // Problem + Literature + Hypothesis pre-approved upstream;
        // land on Hypotheses so the user can pick + run Design next.
        qs = "?tab=hypotheses"
      } else if (mode === "from-plan") {
        // Plan stashed onto problem; land on Literature so the user
        // can confirm sources before generating.
        qs = "?tab=literature"
      }
      router.push(`/${locale}/${wsId}/designs/${created.id}${qs}`)
    } catch (error) {
      console.error("Failed to create design:", error)
      toast.error("Failed to create design.")
    } finally {
      setCreating(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && canSubmit) {
      e.preventDefault()
      void handleCreate()
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="bg-rust-soft text-rust flex size-9 shrink-0 items-center justify-center rounded-md">
              <HeaderIcon size={18} />
            </div>
            <div className="min-w-0">
              <DialogTitle>{copy.title}</DialogTitle>
              <DialogDescription className="mt-0.5 text-[13px] leading-relaxed">
                {copy.subtitle}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="design-name">Name</Label>
            <Input
              id="design-name"
              ref={nameRef}
              placeholder="e.g. Effect of pH on enzyme activity"
              value={name}
              onChange={e => setName(e.target.value)}
              onKeyDown={handleKeyDown}
            />
          </div>

          {/* Project picker - scientist's ask. Single dropdown that
              also covers the project-canvas-launched case (parent passes
              `projectId`, we pre-select it but still let the user
              override). */}
          <div className="space-y-1.5">
            <Label htmlFor="design-project">Project</Label>
            <Select
              value={selectedProjectId}
              onValueChange={v => setSelectedProjectId(v as string | "none")}
            >
              <SelectTrigger id="design-project">
                <SelectValue placeholder="Choose a project (optional)" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">No project</SelectItem>
                {projects.map(p => (
                  <SelectItem key={p.id} value={p.id}>
                    {p.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-ink-3 text-[11.5px]">
              Pin the design to a project, or leave at the workspace level.
            </p>
          </div>

          {/* Problem statement field - hidden for from-scratch since the user
              fills it on the Problem page right after this dialog closes
              (avoids asking for the same thing twice). Shown for the other
              modes where it acts as priming context for the agent. */}
          {mode !== "from-scratch" && (
            <div className="space-y-1.5">
              <Label htmlFor="design-problem">Problem statement</Label>
              <Textarea
                id="design-problem"
                rows={2}
                placeholder="What's the research problem or question?"
                value={problem}
                onChange={e => setProblem(e.target.value)}
              />
            </div>
          )}

          {mode === "from-hypothesis" && (
            <div className="space-y-1.5">
              <Label htmlFor="design-hypothesis">
                Hypothesis <span className="text-rust">*</span>
              </Label>
              <Textarea
                id="design-hypothesis"
                rows={4}
                placeholder="State the hypothesis you want to test. Shadow AI skips hypothesis generation and jumps to experiment design from here."
                value={hypothesis}
                onChange={e => setHypothesis(e.target.value)}
              />
              <p className="text-ink-3 text-[11.5px]">
                Problem, Literature, and Hypothesis phases will be auto-marked
                as approved so you land on the Design stage ready to generate.
              </p>
            </div>
          )}

          {mode === "from-plan" && (
            <div className="space-y-1.5">
              <Label htmlFor="design-plan">
                Existing plan / draft procedure{" "}
                <span className="text-rust">*</span>
              </Label>
              <Textarea
                id="design-plan"
                rows={8}
                placeholder="Paste the draft protocol, SOP excerpt, or planned procedure. Bullets, numbered steps, rough tables - any structure is fine."
                value={planText}
                onChange={e => setPlanText(e.target.value)}
                className="font-mono text-[13px]"
              />
              <p className="text-ink-3 text-[11.5px]">
                The design agent will slot this into the SOP sections and
                complete the missing parts (materials math, stats, safety).
              </p>
            </div>
          )}

          {isExternalMode && (
            <div className="space-y-1.5">
              <Label htmlFor="design-external">
                Existing design <span className="text-rust">*</span>
                <span className="text-ink-3 ml-1 text-[11px] font-normal">
                  paste or upload below
                </span>
              </Label>
              <Textarea
                id="design-external"
                rows={8}
                placeholder="Paste the design you want Shadow to review (sections, protocol, statistical plan, sample sizes - anything you have)."
                value={externalDesignText}
                onChange={e => setExternalDesignText(e.target.value)}
                className="font-mono text-[13px]"
              />
              <p className="text-ink-3 text-[11.5px]">
                {mode === "check-stats"
                  ? "Shadow will run a statistical review (power, test choice, sample size, threats to validity)."
                  : "Shadow will produce a dated execution plan with owners and checkpoints from this design."}
              </p>
            </div>
          )}

          {/* Attachments field: external modes accept the pasted-design's
              source files (PDFs, CSVs, etc); from-hypothesis now also
              accepts PDFs so scientists can drop in supporting papers
              next to the hypothesis they're seeding (per scientist
              ask). From-scratch + from-plan continue to skip the
              picker - those flows upload from the Literature tab. */}
          {canAttachFiles && (
            <div className="space-y-1.5">
              <Label htmlFor="design-attachments">
                {mode === "from-hypothesis"
                  ? "Supporting papers"
                  : "Attachments"}
                <span className="text-ink-3 ml-1 text-[11px] font-normal">
                  {mode === "from-hypothesis"
                    ? "pdf - optional"
                    : "pdf, csv, docx, txt - optional"}
                </span>
              </Label>
              <label
                htmlFor="design-attachments"
                className="border-line bg-paper-2 hover:border-line-strong text-ink-3 hover:text-ink flex cursor-pointer items-center gap-2 rounded-md border border-dashed px-3 py-2.5 text-[12.5px]"
              >
                <IconPaperclip size={14} />
                <span>Click to add files</span>
                <input
                  id="design-attachments"
                  type="file"
                  multiple
                  accept={ACCEPTED_UPLOAD_TYPES}
                  className="hidden"
                  onChange={e => {
                    const list = Array.from(e.target.files ?? [])
                    if (list.length) {
                      setAttachedFiles(prev => [...prev, ...list])
                    }
                    e.currentTarget.value = ""
                  }}
                />
              </label>
              {attachedFiles.length > 0 && (
                <ul className="space-y-1">
                  {attachedFiles.map((f, i) => (
                    <li
                      key={`${f.name}-${i}`}
                      className="border-line bg-surface text-ink-2 flex items-center justify-between rounded-md border px-2.5 py-1.5 text-[12px]"
                    >
                      <span className="min-w-0 truncate">
                        {f.name}{" "}
                        <span className="text-ink-3 ml-1 font-mono text-[10.5px]">
                          {(f.size / 1024).toFixed(1)} KB
                        </span>
                      </span>
                      <button
                        type="button"
                        onClick={() =>
                          setAttachedFiles(prev =>
                            prev.filter((_, idx) => idx !== i)
                          )
                        }
                        className="text-ink-3 hover:text-destructive"
                        aria-label={`Remove ${f.name}`}
                      >
                        <IconX size={13} />
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant="default"
            onClick={() => onOpenChange(false)}
            disabled={creating}
          >
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleCreate}
            disabled={!canSubmit}
            className={cn(creating && "opacity-80")}
          >
            {creating ? "Creating…" : copy.cta}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
