"use client"

import {
  IconBulb,
  IconChartBar,
  IconClipboardText,
  IconPaperclip,
  IconSparkles,
  IconX
} from "@tabler/icons-react"
import { useParams, useRouter } from "next/navigation"
import { FC, useContext, useEffect, useRef, useState } from "react"
import { toast } from "sonner"

import { ChatbotUIContext } from "@/context/context"
import { useDesignContext } from "@/context/designcontext"
import { linkDesignToProject } from "@/db/designs"
import { createDesign, updateDesign } from "@/db/designs-firestore"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"

/**
 * CreateDesign supports three creation modes:
 *
 *   "from-scratch"   — name only; user fills problem/literature/hypotheses/design.
 *   "from-hypothesis" — user supplies a hypothesis up front; design is seeded
 *                       with that hypothesis pre-approved so the user can
 *                       generate an experiment design immediately.
 *   "from-plan"      — user pastes a draft procedure; stored on the design
 *                       so the design-generation agent uses it as priming
 *                       context. The pipeline still fills the SOP sections.
 */
/**
 * Modes the create-design dialog supports.
 *
 * Shadow-generated flows:
 *   "from-scratch"     — full 5-stage flow
 *   "from-hypothesis"  — user supplies hypothesis, jump to design phase
 *   "from-plan"        — user pastes draft procedure, agent fills SOP gaps
 *
 * External-design flows (operate on a design the user brings in, NOT one
 * generated by Shadow AI):
 *   "check-stats"      — user pastes / uploads an existing design; Shadow
 *                         reviews the stats plan (power, test choice, n)
 *   "make-plan"        — user pastes / uploads an existing design; Shadow
 *                         produces a dated execution plan
 */
export type CreateDesignMode =
  | "from-scratch"
  | "from-hypothesis"
  | "from-plan"
  | "check-stats"
  | "make-plan"

const EXTERNAL_DESIGN_MODES: CreateDesignMode[] = ["check-stats", "make-plan"]

interface CreateDesignProps {
  isOpen: boolean
  onOpenChange: (isOpen: boolean) => void
  projectId?: string | null
  mode?: CreateDesignMode
  /** Optional seed text from the dashboard quick-start composer. */
  initialQuery?: string
}

const MODE_COPY: Record<
  CreateDesignMode,
  {
    title: string
    subtitle: string
    icon: typeof IconSparkles
    cta: string
  }
> = {
  "from-scratch": {
    title: "New design",
    subtitle:
      "We'll walk the 5-stage flow: Problem → Literature → Hypotheses → Design.",
    icon: IconSparkles,
    cta: "Create"
  },
  "from-hypothesis": {
    title: "Design from a hypothesis",
    subtitle:
      "You supply the hypothesis; Shadow AI jumps to experiment design. Problem + Literature + Hypothesis phases are pre-approved.",
    icon: IconBulb,
    cta: "Seed and open"
  },
  "from-plan": {
    title: "Structure an existing plan",
    subtitle:
      "Paste your draft procedure. The design agent will slot it into the SOP sections and fill the gaps.",
    icon: IconClipboardText,
    cta: "Create"
  },
  "check-stats": {
    title: "Check a design statistically",
    subtitle:
      "Paste or upload an existing design (from a paper, a colleague, or your draft). Shadow reviews the stats plan: power, test choice, sample size.",
    icon: IconChartBar,
    cta: "Check stats"
  },
  "make-plan": {
    title: "Make a plan for a design",
    subtitle:
      "Paste or upload an existing design. Shadow produces a dated execution plan with owners and checkpoints.",
    icon: IconClipboardText,
    cta: "Make a plan"
  }
}

const ACCEPTED_UPLOAD_TYPES =
  ".pdf,.csv,.docx,.txt,application/pdf,text/csv,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document"

export const CreateDesign: FC<CreateDesignProps> = ({
  isOpen,
  onOpenChange,
  projectId,
  mode = "from-scratch",
  initialQuery = ""
}) => {
  const { profile, selectedWorkspace, designs, setDesigns } =
    useContext(ChatbotUIContext)
  const { setSelectedDesign } = useDesignContext()

  const router = useRouter()
  const params = useParams()

  const [name, setName] = useState("")
  const [problem, setProblem] = useState("")
  const [hypothesis, setHypothesis] = useState("")
  const [planText, setPlanText] = useState("")
  /** External-design content for check-stats / make-plan modes. */
  const [externalDesignText, setExternalDesignText] = useState("")
  /** Files attached to the new design (every mode supports this). */
  const [attachedFiles, setAttachedFiles] = useState<File[]>([])
  const [creating, setCreating] = useState(false)
  const nameRef = useRef<HTMLInputElement>(null)

  const isExternalMode = EXTERNAL_DESIGN_MODES.includes(mode)

  useEffect(() => {
    if (!isOpen) return
    // Seed fields on open. If the user composed a query on the dashboard,
    // prefill it into the primary text field for the current mode.
    setName(initialQuery.slice(0, 80))
    setProblem(mode === "from-hypothesis" ? initialQuery : initialQuery)
    setHypothesis("")
    setPlanText("")
    setExternalDesignText("")
    setAttachedFiles([])
    setTimeout(() => nameRef.current?.focus(), 0)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, mode])

  if (!profile || !selectedWorkspace) return null

  const copy = MODE_COPY[mode]
  const HeaderIcon = copy.icon

  const canSubmit = (() => {
    if (creating) return false
    if (!name.trim()) return false
    if (mode === "from-hypothesis" && hypothesis.trim().length < 10)
      return false
    if (mode === "from-plan" && planText.trim().length < 20) return false
    if (isExternalMode) {
      // Need either pasted content or an uploaded file to operate on.
      const hasPaste = externalDesignText.trim().length >= 20
      const hasFile = attachedFiles.length > 0
      if (!hasPaste && !hasFile) return false
    }
    return true
  })()

  const handleCreate = async () => {
    const trimmedName = name.trim()
    if (!trimmedName) return

    setCreating(true)
    try {
      // 1) Create the base design row (Supabase).
      const created = await createDesign(
        {
          user_id: profile.user_id,
          name: trimmedName,
          problem: problem.trim() || trimmedName,
          description: (problem.trim() || trimmedName).slice(0, 240),
          sharing: "private" as const,
          objectives: [],
          variables: [],
          specialConsiderations: [],
          project_id: projectId ?? null
        },
        selectedWorkspace.id
      )

      if (projectId && created?.id && created.project_id !== projectId) {
        try {
          await linkDesignToProject(created.id, projectId)
          created.project_id = projectId
        } catch (err) {
          console.warn("Failed to link new design to project:", err)
        }
      }

      // 2) Mode-specific post-create seeding.
      // From-scratch: stash the user-supplied title + problem into structured
      // content.problem so the design-detail loader reads from there directly
      // (avoiding the data.description fallback path which has historically
      // produced subtle prefill bugs).
      if (mode === "from-scratch" && created?.id) {
        const problemText = problem.trim()
        if (problemText) {
          const seededContent = {
            schemaVersion: 2,
            approvedPhases: [],
            problem: {
              title: trimmedName,
              problemStatement: problemText,
              objective: "",
              goal: ""
            },
            papers: [],
            hypotheses: []
          }
          try {
            await updateDesign(created.id, {
              content: JSON.stringify(seededContent)
            })
          } catch (err) {
            console.warn("Failed to seed from-scratch content:", err)
          }
        }
      }

      // For hypothesis mode, pre-seed the design content so the downstream
      // design-detail page opens ready to generate an experiment design
      // (problem / literature / hypotheses phases are marked approved).
      if (mode === "from-hypothesis" && created?.id) {
        const hypText = hypothesis.trim()
        const problemText = problem.trim() || trimmedName
        const seededContent = {
          schemaVersion: 2,
          approvedPhases: ["problem", "literature", "hypotheses"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText
          },
          papers: [],
          hypotheses: [
            {
              id: `h-${Date.now()}`,
              text: hypText,
              reasoning: "User-provided hypothesis.",
              basedOnPaperIds: [],
              selected: true,
              userSupplied: true
            }
          ]
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn(
            "Failed to seed hypothesis-mode content; user can re-enter in the design:",
            err
          )
        }
      }

      if (mode === "from-plan" && created?.id) {
        // Stash the user-supplied plan on the design's problem text so the
        // generation agents pick it up as priming context. Backend prompt
        // changes can promote this to its own field later.
        const planned = planText.trim()
        const problemText = problem.trim() || trimmedName
        const seededContent = {
          schemaVersion: 2,
          approvedPhases: ["problem"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText,
            userProvidedPlan: planned
          },
          papers: [],
          hypotheses: []
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn("Failed to seed plan-mode content:", err)
        }
      }

      // External-design modes (check-stats / make-plan): the design is
      // brought in by the user — Shadow AI does NOT generate it. We stuff
      // the pasted text into a single synthetic generated-design so the
      // existing stats-review and make-plan endpoints (which read from
      // `content.designs[]`) can operate on it.
      if (isExternalMode && created?.id) {
        const ext = externalDesignText.trim()
        const problemText = problem.trim() || trimmedName
        const designId = `ext-${Date.now()}`
        const seededContent = {
          schemaVersion: 2,
          external: true,
          approvedPhases: ["problem", "literature", "hypotheses", "design"],
          problem: {
            title: trimmedName,
            problemStatement: problemText,
            objective: problemText,
            goal: problemText
          },
          papers: [],
          hypotheses: [],
          designs: [
            {
              id: designId,
              title: trimmedName,
              hypothesisId: null,
              external: true,
              sections: [
                {
                  heading: "External Design",
                  body: ext
                }
              ],
              attachments: attachedFiles.map(f => ({
                name: f.name,
                size: f.size,
                type: f.type
              }))
            }
          ]
        }
        try {
          await updateDesign(created.id, {
            content: JSON.stringify(seededContent)
          })
        } catch (err) {
          console.warn("Failed to seed external-design content:", err)
        }
      }

      // Capture file metadata on every other mode too so downstream agents
      // can see what the user attached. Real upload to storage is wired up
      // by the design-detail page's existing PDF-upload handler — for now
      // we record names + sizes only.
      if (!isExternalMode && attachedFiles.length > 0 && created?.id) {
        try {
          await updateDesign(created.id, {
            content_attachments: attachedFiles.map(f => ({
              name: f.name,
              size: f.size,
              type: f.type
            }))
          } as any)
        } catch (err) {
          console.warn("Failed to record attachment metadata:", err)
        }
      }

      setDesigns([created, ...designs])
      setSelectedDesign(created)

      const locale = (params.locale as string) ?? "en"
      const wsId = params.workspaceid as string
      // External-design modes auto-trigger the matching agent on landing.
      const autoQs =
        mode === "check-stats"
          ? "?auto=stats-review"
          : mode === "make-plan"
            ? "?auto=make-plan"
            : ""
      router.push(`/${locale}/${wsId}/designs/${created.id}${autoQs}`)
    } catch (error) {
      console.error("Failed to create design:", error)
      toast.error("Failed to create design.")
    } finally {
      setCreating(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && canSubmit) {
      e.preventDefault()
      void handleCreate()
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <div className="bg-rust-soft text-rust flex size-9 shrink-0 items-center justify-center rounded-md">
              <HeaderIcon size={18} />
            </div>
            <div className="min-w-0">
              <DialogTitle>{copy.title}</DialogTitle>
              <DialogDescription className="mt-0.5 text-[13px] leading-relaxed">
                {copy.subtitle}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="design-name">Name</Label>
            <Input
              id="design-name"
              ref={nameRef}
              placeholder="e.g. Effect of pH on enzyme activity"
              value={name}
              onChange={e => setName(e.target.value)}
              onKeyDown={handleKeyDown}
            />
          </div>

          {/* Problem is useful for every mode but optional for from-scratch. */}
          <div className="space-y-1.5">
            <Label htmlFor="design-problem">
              Problem statement
              {mode === "from-scratch" && (
                <span className="text-ink-3 ml-1 text-[11px] font-normal">
                  (optional — you can fill in later)
                </span>
              )}
            </Label>
            <Textarea
              id="design-problem"
              rows={2}
              placeholder="What's the research problem or question?"
              value={problem}
              onChange={e => setProblem(e.target.value)}
            />
          </div>

          {mode === "from-hypothesis" && (
            <div className="space-y-1.5">
              <Label htmlFor="design-hypothesis">
                Hypothesis <span className="text-rust">*</span>
              </Label>
              <Textarea
                id="design-hypothesis"
                rows={4}
                placeholder="State the hypothesis you want to test. Shadow AI skips hypothesis generation and jumps to experiment design from here."
                value={hypothesis}
                onChange={e => setHypothesis(e.target.value)}
              />
              <p className="text-ink-3 text-[11.5px]">
                Problem, Literature, and Hypothesis phases will be auto-marked
                as approved so you land on the Design stage ready to generate.
              </p>
            </div>
          )}

          {mode === "from-plan" && (
            <div className="space-y-1.5">
              <Label htmlFor="design-plan">
                Existing plan / draft procedure{" "}
                <span className="text-rust">*</span>
              </Label>
              <Textarea
                id="design-plan"
                rows={8}
                placeholder="Paste the draft protocol, SOP excerpt, or planned procedure. Bullets, numbered steps, rough tables — any structure is fine."
                value={planText}
                onChange={e => setPlanText(e.target.value)}
                className="font-mono text-[13px]"
              />
              <p className="text-ink-3 text-[11.5px]">
                The design agent will slot this into the SOP sections and
                complete the missing parts (materials math, stats, safety).
              </p>
            </div>
          )}

          {isExternalMode && (
            <div className="space-y-1.5">
              <Label htmlFor="design-external">
                Existing design <span className="text-rust">*</span>
                <span className="text-ink-3 ml-1 text-[11px] font-normal">
                  paste or upload below
                </span>
              </Label>
              <Textarea
                id="design-external"
                rows={8}
                placeholder="Paste the design you want Shadow to review (sections, protocol, statistical plan, sample sizes — anything you have)."
                value={externalDesignText}
                onChange={e => setExternalDesignText(e.target.value)}
                className="font-mono text-[13px]"
              />
              <p className="text-ink-3 text-[11.5px]">
                {mode === "check-stats"
                  ? "Shadow will run a statistical review (power, test choice, sample size, threats to validity)."
                  : "Shadow will produce a dated execution plan with owners and checkpoints from this design."}
              </p>
            </div>
          )}

          {/* Attachments — supported by every mode. PDFs, CSVs, and DOCX
              files are recorded on the design so downstream agents can read
              them as priming context. Real upload-to-storage is performed
              by the design-detail page; here we just capture metadata and
              keep the picked File objects for that next step. */}
          <div className="space-y-1.5">
            <Label htmlFor="design-attachments">
              Attachments
              <span className="text-ink-3 ml-1 text-[11px] font-normal">
                pdf, csv, docx, txt — optional
              </span>
            </Label>
            <label
              htmlFor="design-attachments"
              className="border-line bg-paper-2 hover:border-line-strong text-ink-3 hover:text-ink flex cursor-pointer items-center gap-2 rounded-md border border-dashed px-3 py-2.5 text-[12.5px]"
            >
              <IconPaperclip size={14} />
              <span>Click to add files</span>
              <input
                id="design-attachments"
                type="file"
                multiple
                accept={ACCEPTED_UPLOAD_TYPES}
                className="hidden"
                onChange={e => {
                  const list = Array.from(e.target.files ?? [])
                  if (list.length) {
                    setAttachedFiles(prev => [...prev, ...list])
                  }
                  e.currentTarget.value = ""
                }}
              />
            </label>
            {attachedFiles.length > 0 && (
              <ul className="space-y-1">
                {attachedFiles.map((f, i) => (
                  <li
                    key={`${f.name}-${i}`}
                    className="border-line bg-surface text-ink-2 flex items-center justify-between rounded-md border px-2.5 py-1.5 text-[12px]"
                  >
                    <span className="min-w-0 truncate">
                      {f.name}{" "}
                      <span className="text-ink-3 ml-1 font-mono text-[10.5px]">
                        {(f.size / 1024).toFixed(1)} KB
                      </span>
                    </span>
                    <button
                      type="button"
                      onClick={() =>
                        setAttachedFiles(prev =>
                          prev.filter((_, idx) => idx !== i)
                        )
                      }
                      className="text-ink-3 hover:text-destructive"
                      aria-label={`Remove ${f.name}`}
                    >
                      <IconX size={13} />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button
            variant="default"
            onClick={() => onOpenChange(false)}
            disabled={creating}
          >
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleCreate}
            disabled={!canSubmit}
            className={cn(creating && "opacity-80")}
          >
            {creating ? "Creating…" : copy.cta}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
