-- Backfill existing `file_items` rows into `rag_items` using the
-- already-computed OpenAI embeddings (no re-embedding cost). Idempotent
-- via the (source_type, source_id, workspace_id, chunk_index,
-- index_version) unique constraint + `ON CONFLICT DO NOTHING`.
--
-- Decisions baked in (per /Users/piyush/.claude/plans/rosy-rolling-flute.md):
--   - source_type = 'file'
--   - contextualized_content := content (skip Haiku for files; v1 ships
--     without contextual blurbs for legacy file rows — natural metadata
--     like filename + page headers does most of the work)
--   - openai_embedding reused as-is (1536d already)
--   - tsvector_content auto-generated by the table
--   - chunk_index = row_number per file ordered by file_items.created_at
--     so chunks land in original document order
--   - one row per (file, workspace) pair via JOIN on file_workspaces
--   - Skips rows where the file's workspace owner ≠ file_items.user_id —
--     RLS would block such a row anyway, and a workspace shared with
--     someone else's file would point at the wrong owner.
--
-- Safe to re-run.

INSERT INTO rag_items (
  source_type,
  source_id,
  workspace_id,
  project_id,
  user_id,
  chunk_index,
  content,
  contextualized_content,
  openai_embedding,
  source_title,
  source_url,
  source_section,
  source_updated_at,
  metadata,
  index_version
)
SELECT
  'file'::rag_source_type AS source_type,
  fi.file_id::TEXT        AS source_id,
  fw.workspace_id         AS workspace_id,
  NULL::UUID              AS project_id,
  fi.user_id              AS user_id,
  ROW_NUMBER() OVER (
    PARTITION BY fi.file_id, fw.workspace_id
    ORDER BY fi.created_at, fi.id
  ) - 1                   AS chunk_index,
  fi.content              AS content,
  fi.content              AS contextualized_content,
  fi.openai_embedding     AS openai_embedding,
  f.name                  AS source_title,
  '/files/' || f.id::TEXT AS source_url,
  NULL                    AS source_section,
  COALESCE(f.updated_at, f.created_at) AS source_updated_at,
  jsonb_build_object(
    'mime_type', f.type,
    'description', f.description
  )                       AS metadata,
  1                       AS index_version
FROM file_items fi
JOIN files f          ON f.id = fi.file_id
JOIN file_workspaces fw ON fw.file_id = fi.file_id
WHERE fw.user_id = fi.user_id   -- belt+suspenders: skip cross-owner rows
ON CONFLICT (source_type, source_id, workspace_id, chunk_index, index_version)
DO NOTHING;

-- Mark every backfilled file as "ready" so the cron sweep doesn't
-- redundantly refire `rag.doc.changed` for them.
UPDATE files
SET
  index_status    = 'ready',
  last_indexed_at = COALESCE(last_indexed_at, now()),
  index_version   = 1
WHERE index_status <> 'ready';
